# Generated by Django 4.2.16 on 2026-05-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('team_a_name', models.CharField(default='Thunder XI', max_length=100)),
                ('team_b_name', models.CharField(default='Storm XI', max_length=100)),
                ('match_date', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('winner_team', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
