# Generated by Django 4.2.16 on 2026-05-02 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs_scored', models.IntegerField(default=0)),
                ('balls_faced', models.IntegerField(default=0)),
                ('fours', models.IntegerField(default=0)),
                ('sixes', models.IntegerField(default=0)),
                ('is_out', models.BooleanField(default=True)),
                ('overs_bowled', models.FloatField(default=0)),
                ('wickets_taken', models.IntegerField(default=0)),
                ('runs_conceded', models.IntegerField(default=0)),
                ('maidens', models.IntegerField(default=0)),
                ('catches', models.IntegerField(default=0)),
                ('run_outs', models.IntegerField(default=0)),
                ('stumpings', models.IntegerField(default=0)),
                ('base_points', models.FloatField(default=0)),
                ('fantasy_points', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='players.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='tournaments.tournament')),
            ],
            options={
                'unique_together': {('player', 'tournament')},
            },
        ),
    ]
