# Generated by Django 4.2.16 on 2026-05-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerperformance',
            name='points_breakdown',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
