# Generated by Django 4.2.16 on 2026-05-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_playerperformance_points_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerperformance',
            name='best_bowling_runs',
            field=models.IntegerField(default=0, help_text='Runs conceded in that best bowling spell'),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='best_bowling_wkts',
            field=models.IntegerField(default=0, help_text='Best bowling wickets in one match'),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='best_score_not_out',
            field=models.BooleanField(default=False, help_text='Was not out in that best innings?'),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='best_score_runs',
            field=models.IntegerField(default=0, help_text='Highest score in a single innings'),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='ducks',
            field=models.IntegerField(default=0, help_text='Number of duck dismissals (0 runs, out)'),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='innings_played',
            field=models.IntegerField(default=1, help_text='Number of innings batted'),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='matches_played',
            field=models.IntegerField(default=1, help_text='Number of matches played in this tournament day'),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='missed_catches',
            field=models.IntegerField(default=0, help_text='Dropped catches — each deducts 5 pts'),
        ),
        migrations.AlterField(
            model_name='playerperformance',
            name='is_out',
            field=models.BooleanField(default=True, help_text='Was out at least once (for duck calculation)'),
        ),
        migrations.AlterField(
            model_name='playerperformance',
            name='runs_scored',
            field=models.IntegerField(default=0, help_text='Total runs across all matches'),
        ),
        migrations.AlterField(
            model_name='playerperformance',
            name='wickets_taken',
            field=models.IntegerField(default=0, help_text='Total wickets across all matches'),
        ),
    ]
