# Generated by Django 4.2.16 on 2026-05-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(choices=[('Thunder XI', 'Thunder XI'), ('Storm XI', 'Storm XI')], max_length=50)),
                ('role', models.CharField(choices=[('BAT', 'Batsman'), ('BOWL', 'Bowler'), ('AR', 'All-Rounder'), ('WK', 'Wicket-Keeper')], max_length=10)),
                ('price', models.DecimalField(decimal_places=1, default=8.0, max_digits=4)),
                ('playing_style', models.CharField(choices=[('Attacking', 'Attacking'), ('Defensive', 'Defensive'), ('Balanced', 'Balanced')], default='Balanced', max_length=20)),
                ('batting_rating', models.FloatField(default=5.0)),
                ('bowling_rating', models.FloatField(default=5.0)),
                ('fielding_rating', models.FloatField(default=5.0)),
                ('best_hitting_zone', models.CharField(choices=[('Off Side', 'Off Side'), ('Leg Side', 'Leg Side'), ('Straight', 'Straight'), ('All Around', 'All Around')], default='All Around', max_length=20)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='players/')),
                ('matches_played', models.IntegerField(default=0)),
                ('total_runs', models.IntegerField(default=0)),
                ('total_wickets', models.IntegerField(default=0)),
                ('average', models.FloatField(default=0.0)),
                ('strike_rate', models.FloatField(default=0.0)),
                ('economy', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('jersey_number', models.IntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-price', 'name'],
            },
        ),
    ]
