# Generated by Django 4.2.16 on 2026-05-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(choices=[('Team A', 'Team A'), ('Team B', 'Team B')], max_length=50),
        ),
    ]
