# Generated by Django 4.2.16 on 2026-05-08 07:59

from django.db import migrations, models
import players.models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=players.models.player_image_path),
        ),
    ]
