# Generated by Django 4.2.16 on 2026-05-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_player_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='average',
            new_name='overs_bowled',
        ),
        migrations.RemoveField(
            model_name='player',
            name='economy',
        ),
        migrations.RemoveField(
            model_name='player',
            name='strike_rate',
        ),
        migrations.AddField(
            model_name='player',
            name='balls_faced',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='best_bowling_runs',
            field=models.IntegerField(default=999, help_text='Best bowling runs conceded'),
        ),
        migrations.AddField(
            model_name='player',
            name='best_bowling_wkts',
            field=models.IntegerField(default=0, help_text='Best bowling wickets'),
        ),
        migrations.AddField(
            model_name='player',
            name='catches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='ducks',
            field=models.IntegerField(default=0, help_text='Number of duck dismissals'),
        ),
        migrations.AddField(
            model_name='player',
            name='fifties',
            field=models.IntegerField(default=0, help_text='Number of 50+ scores'),
        ),
        migrations.AddField(
            model_name='player',
            name='fours',
            field=models.IntegerField(default=0, help_text='Total boundaries hit'),
        ),
        migrations.AddField(
            model_name='player',
            name='highest_score',
            field=models.IntegerField(default=0, help_text='Highest individual score'),
        ),
        migrations.AddField(
            model_name='player',
            name='hundreds',
            field=models.IntegerField(default=0, help_text='Number of 100+ scores'),
        ),
        migrations.AddField(
            model_name='player',
            name='innings_played',
            field=models.IntegerField(default=0, help_text='Total innings batted'),
        ),
        migrations.AddField(
            model_name='player',
            name='maidens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='missed_catches',
            field=models.IntegerField(default=0, help_text='Dropped catches'),
        ),
        migrations.AddField(
            model_name='player',
            name='run_outs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='runs_conceded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='sixes',
            field=models.IntegerField(default=0, help_text='Total sixes hit'),
        ),
        migrations.AddField(
            model_name='player',
            name='stumpings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_fantasy_points',
            field=models.FloatField(default=0.0, help_text='Cumulative fantasy points'),
        ),
        migrations.AlterField(
            model_name='player',
            name='matches_played',
            field=models.IntegerField(default=0, help_text='Total matches played'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(choices=[('Boundary Boys', 'Boundary Boys'), ('Gaule Gugglers', 'Gaule Gugglers')], max_length=50),
        ),
    ]
